### PR TITLE
Adds a color invert button to the top right

### PR DESCRIPTION
**Pull request by Divran**
Source for icon image:
https://material.io/tools/icons/?search=invert&icon=invert_colors&style=baseline

### CODE REVIEW

**Comment by Divran** [comment]
Currently this does not save the user's settings in cookies. I could easily add that if you want

**Comment by ctwelve** [comment]
This is great! Can you save the user's preference so they don't have to keep clicking the button?

**Comment by ctwelve** [comment]
> I could add that if you want

Please!

**Review by ctwelve — APPROVED** [review]
Looks good to me! Thanks for the work!

**Pull request merged**
