### PR TITLE
Clientside javascript EPUB generator

### PR DESCRIPTION
**Pull request by Divran**
Also threw in some minor fixes for the color inverter.

### CODE REVIEW

**Comment by Divran** [comment]
~~The only thing missing is a cover image. It'd be great if they were attached to the html somehow via hugo, so that I could easily retrieve them. Currently, whatever epub viewer you use will just show you some default boring gray square.~~

**Comment by Divran** [comment]
Oh and another thing is that there doesn't seem to be any way to get the title of the series, only the title of the current chapter. It'd be great if that could be fixed somehow.

**Comment by Divran** [comment]
Here's a video of the cover image selector in action
https://drive.google.com/file/d/1hLGuObmiMkq4ye9tLOXzIpKh49bTbdc5/view?usp=sharing
Note that this video is taken before I added a "skip (no cover)" button.
~~I would like to be able to use Hambone's cover images instead, but until that option is available, this is the best I can do.~~

**Comment by Divran** [comment]
Here's an image of the auto-detector in action
image

**Comment by Divran** [comment]
@ctwelve @HamboneHFY The cover image auto detector checks for an image with the exact same name as the `.md` file, except in the `/static/images/` folder. See this PR https://github.com/deathworlders/online/pull/80

This means, to make use of this feature, the only thing you need to do is take the same image that you already upload to patreon every month, and place it in the `/static/images/` folder of the other repository (the main site one, not this theme repo). Then, rename the image so that the file name is identical to the `.md` file, except with a file ending of `.jpg` instead of `.md` of course. That's it!

It'll only work with `.jpg` because my code only checks for that file type.

Let me know if you have any questions!

**Comment by Divran** [comment]
This is ready to be merged now.

**Review by ctwelve — APPROVED** [review]
LEGEND. ARY.

**Comment by ctwelve** [comment]
Okay. This is seriously above and beyond the mark. Well done!

**Pull request merged**
